In [1]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf
from tensorflow.keras import Model, layers
import numpy as np

In [15]:
from tensorflow.keras.optimizers import Adam

In [2]:
inputs = tf.keras.Input(shape=(3,))

In [3]:
outputs = tf.keras.layers.Dense(2)(inputs)

In [16]:
model = tf.keras.models.Model(inputs=inputs, outputs=outputs)

In [22]:
model.compile(optimizer= tf.keras.optimizers.Adam(lr = 1e-3), loss="mse", metrics=["mae"])

In [23]:
model.metrics_names

['loss', 'mae']

In [24]:
x = np.random.random((2, 3))

In [25]:
x

array([[0.17297944, 0.3353891 , 0.90218923],
       [0.45110696, 0.67868469, 0.95718505]])

In [42]:
x.shape

(2, 3)

In [68]:
y = np.random.randint(0, 2, (2, 2))

In [69]:
y

array([[0, 1],
       [0, 1]])

In [70]:
y.shape

(2, 2)

In [71]:
model.fit(x, y)

Train on 2 samples
2/2 [==============================] - 0s 3ms/sample - loss: 0.6927 - mae: 0.7566


In [72]:
x[0].shape

(3,)

In [73]:
p = np.random.random((5, 3))

In [74]:
p

array([[0.06803375, 0.89778439, 0.25311242],
       [0.91796515, 0.14161487, 0.50878824],
       [0.57772055, 0.9358804 , 0.01719004],
       [0.82598731, 0.52045885, 0.68711121],
       [0.80453657, 0.95001576, 0.04570306]])

In [75]:
p.shape

(5, 3)

In [89]:
p_sample = np.expand_dims(p[0], axis =0)

In [90]:
p_sample.shape

(1, 3)

In [91]:
model.predict(p_sample,batch_size=1 )

array([[0.6342789, 0.1124258]], dtype=float32)

In [92]:
model.predict(p,batch_size=1 )

array([[ 0.6342789 ,  0.1124258 ],
       [ 0.16799676, -0.61186504],
       [ 0.6653093 , -0.26724666],
       [ 0.4364074 , -0.4728522 ],
       [ 0.6863369 , -0.42830685]], dtype=float32)

## Few lines to create a Model

In [94]:
inputs_ = tf.keras.Input(shape=(3,))
d = tf.keras.layers.Dense(2, name='out')
output_1 = d(inputs_)
output_2 = d(inputs_)
model_ = tf.keras.models.Model(
   inputs=inputs_, outputs=[output_1, output_2])
model_.compile(optimizer="Adam", loss="mse", metrics=["mae", "acc"])
model_.fit(x, (y,y))
model_.metrics_names

Train on 2 samples
2/2 [==============================] - 0s 231ms/sample - loss: 0.0234 - out_loss: 0.0117 - out_1_loss: 0.0117 - out_mae: 0.0802 - out_acc: 1.0000 - out_1_mae: 0.0802 - out_1_acc: 1.0000


['loss',
 'out_loss',
 'out_1_loss',
 'out_mae',
 'out_acc',
 'out_1_mae',
 'out_1_acc']