In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
# Create TensorFlow object called hello_constant
hello_constant = tf.constant('Hello World!')

In [4]:
print("Tensor:", hello_constant)
print("Value :", hello_constant.numpy())

Tensor: tf.Tensor(b'Hello World!', shape=(), dtype=string)
Value : b'Hello World!'


# Variables are manipulated via the tf.Variable class.
# A tf.Variable represents a tensor whose value can be changed by running ops on it.
# Specific ops allow you to read and modify the values of this tensor.

## Creating a Variable

In [5]:
tf.Variable("hello")

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello'>

In [6]:
variable = tf.Variable(1000)
print("tensor:", variable)
print("value:", variable.numpy())

tensor: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1000>
value: 1000


In [7]:
variable = variable * 10
print("value:", variable.numpy())

value: 10000


In [8]:
variable2 = tf.Variable(2)

In [9]:
variable2.assign_add(37)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=39>

In [10]:

print("value:", variable2.numpy())

value: 39


In [11]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
###======================================= assign value  ===================================#

a = tf.ones([2,3])
print(a)

# a[0,0] = 10 => TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [13]:
a = tf.Variable(a)
a[0,0].assign(10)
b = a.read_value()
print(b)


tf.Tensor(
[[10.  1.  1.]
 [ 1.  1.  1.]], shape=(2, 3), dtype=float32)


In [14]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)>


In [15]:
###======================================= add, multiply, div. etc ===================================#

a = tf.constant(2)
b = tf.constant(3)

print("a + b :" , a.numpy() + b.numpy())
print("Addition with constants: ", a+b)
print("Addition with constants: ", tf.add(a, b))
print("a * b :" , a.numpy() * b.numpy())
print("Multiplication with constants: ", a*b)
print("Multiplication with constants: ", tf.multiply(a, b))


a + b : 5
Addition with constants:  tf.Tensor(5, shape=(), dtype=int32)
Addition with constants:  tf.Tensor(5, shape=(), dtype=int32)
a * b : 6
Multiplication with constants:  tf.Tensor(6, shape=(), dtype=int32)
Multiplication with constants:  tf.Tensor(6, shape=(), dtype=int32)


### tf.matmul()

In [16]:
# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.matmul(matrix1, matrix2)
print("Multiplication with matrixes:", product)

# broadcast matrix in Multiplication

print("broadcast matrix in Multiplication:", matrix1 * matrix2)


Multiplication with matrixes: tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
broadcast matrix in Multiplication: tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


In [17]:
###===================================== cast operations =====================================#

a = tf.convert_to_tensor(2.0)
b = tf.cast(a, tf.int32)
print(a, b)


tf.Tensor(2.0, shape=(), dtype=float32) tf.Tensor(2, shape=(), dtype=int32)


In [18]:
print(a.numpy())

2.0


In [19]:
print(b.numpy())

2


In [20]:
###===================================== shape operations ===================================#

a = tf.ones([2,3])
print(a.shape[0], a.shape[1]) # 2, 3
shape = tf.shape(a)           # a tensor
print(shape[0], shape[1])


2 3
tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


In [21]:
a.shape

TensorShape([2, 3])

In [22]:
a.shape[0]

2

In [23]:
import pandas as pd

In [24]:
df = pd.DataFrame({'A': ['male', 'female', 'male'], 'B': ['yes', 'no', 'no'], 'C': [1, 2, 3]})

In [25]:
df

A    B  C
0    male  yes  1
1  female   no  2
2    male   no  3

In [26]:
pd.get_dummies(df, prefix=['A', 'B'])

C  A_female  A_male  B_no  B_yes
0  1         0       1     0      1
1  2         1       0     1      0
2  3         0       1     1      0